### ISSUE TITLE
Fix rendering on Chrome

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber-attic/website#32] opened 2015-04-23 11:03 UTC
See https://twitter.com/markoa/status/591189238013698048

**Comment by jbpros** [comment] 2015-04-29 09:47
Looks like the page is zoomed a lot there. I can reproduce this "issue" with a big zoom level and this mobile layout is expected in that case.

I replied on twitter and am waiting for a reply to confirm it's another problem than a too-high zoom setting. Closing in the meantime.

**Closed as completed by jbpros** 2015-04-29 09:47 UTC
